kind: KubeProxyConfiguration
bindAddress: "{{ ansible_fake0.ipv4.address }}"
healthzBindAddress: "{{ ansible_fake0.ipv4.address }}:10256"
apiVersion: kubeproxy.config.k8s.io/v1alpha1
clientConnection:
  kubeconfig: "/var/lib/kube-proxy/kubeconfig"
mode: "iptables"
clusterCIDR: "{{ cluster_cidr }}"
